<?php
$legalTitle = 'Terms and Conditions';
$legalDescription = 'A clear guide to your account, orders, payments, and deliveries.';
$legalSummary = 'Keep your account details accurate, protect your QR code, and review your order before submitting it.';
$legalActive = 'terms';
$legalSections = [
    ['service', 'Using HydroMIS', '<p>HydroMIS helps customers place water refill orders and helps station staff and riders manage fulfillment and delivery. These terms apply when you use the service. Read the <a href="privacy.php">Privacy Policy</a> to understand how personal information is handled.</p>'],
    ['account', 'Your account and QR code', '<p>Provide accurate registration and delivery details, and keep your contact number up to date. Account access and orders may be subject to station verification or approval.</p><p>Keep your QR code private: it supports account access and may contain personal information. Do not post it publicly or share it with people you do not trust. Contact support if it is lost, exposed, or used without your permission.</p>'],
    ['orders', 'Orders, prices and payments', '<p>Check the items, quantities, delivery address, payment method, and total before submitting an order. Fulfillment depends on stock, station approval, and delivery availability. A submitted order is not a guarantee of delivery.</p><p>Use the payment options shown for your order. Electronic payments may require proof and verification. Discounts and loyalty rewards follow the rules shown in the system; contact the station if a total or points balance appears incorrect.</p>'],
    ['cancellations', 'Cancellations and refunds', '<p>You can cancel an eligible pending order using the cancellation option on the tracking page. Once an order has been approved, started, or completed, contact the station for assistance.</p><p>Cancellation does not mean a payment has already been refunded. Paid GCash or Maya orders may be marked as awaiting a refund. Contact the station with your transaction reference to confirm the refund status and expected timing.</p>'],
    ['delivery', 'Delivery and order concerns', '<p>Provide a reachable contact number and a complete delivery address. Delivery timing and map positions are estimates and can be affected by traffic, connectivity, GPS accuracy, and station workload.</p><p>Report missing items, incorrect quantities, damaged containers, or water quality concerns promptly to the station. Include your order reference and a description so staff can investigate and discuss the appropriate resolution.</p>'],
    ['conduct', 'Responsible use', '<p>Do not access another person\'s account without permission, submit false orders or payment evidence, misuse customer or rider details, or interfere with the system. Account access may be restricted while suspected misuse or security concerns are investigated.</p>'],
    ['availability', 'Availability and changes', '<p>Maintenance, network problems, or service interruptions may temporarily affect access, notifications, and tracking. Contact the station if you need help confirming an order during an interruption.</p><p>These terms may be revised as the service changes. The date on this page identifies the latest revision. Nothing in these terms removes rights or remedies available under applicable law.</p>'],
    ['contact', 'Questions and support', '<p>For order issues, contact the water station handling your order. For HydroMIS account or service questions, email <a href="mailto:hydromis.support@gmail.com">hydromis.support@gmail.com</a>. Include your order reference when relevant, but do not send passwords, your QR code, or unnecessary personal information.</p>']
];
require __DIR__ . '/legal-layout.php';
