<?php

class PgDBCompatResult {
    private array $rows;
    private int $cursor = 0;
    public int $num_rows;
    public function __construct(array $rows) { $this->rows=$rows; $this->num_rows=count($rows); }
    public function fetch_assoc() {
        if (!isset($this->rows[$this->cursor])) return null;
        $row=$this->rows[$this->cursor++];
        foreach ($row as $key=>$value) if (is_string($value) && DataSecurity::isEncrypted($value)) $row[$key]=DataSecurity::decrypt($value);
        return $row;
    }
}

class PgDBCompatStatement {
    private PDOStatement $statement;
    private PgDBCompatConnection $connection;
    private array $values=[];
    public int $affected_rows=0;
    public string $error='';
    public function __construct(PDOStatement $statement,PgDBCompatConnection $connection){$this->statement=$statement;$this->connection=$connection;}
    public function bind_param(string $types,&...$variables):bool{$this->values=[];foreach($variables as &$value)$this->values[]=&$value;return true;}
    public function execute(?array $params=null):bool{
        try{$ok=$this->statement->execute(array_values($params??$this->values));$this->affected_rows=$this->statement->rowCount();$this->connection->statementCompleted($this->affected_rows);return $ok;}
        catch(PDOException $e){$this->error=$e->getMessage();$this->connection->setError($this->error);return false;}
    }
    public function get_result(){return new PgDBCompatResult($this->statement->fetchAll(PDO::FETCH_ASSOC));}
    public function close():bool{$this->statement->closeCursor();return true;}
}

class PgDBCompatConnection {
    public string $connect_error=''; public string $error=''; public int $insert_id=0; public int $affected_rows=0;
    private ?PDO $pdo=null;
    public function __construct($host,$user,$pass,$db,$port=6543){
        try{$dsn="pgsql:host=$host;port=$port;dbname=$db;sslmode=".DB_SSLMODE;$this->pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);$this->pdo->exec("SET TIME ZONE 'Asia/Manila'");$this->pdo->exec(file_get_contents(__DIR__.'/../database/supabase_schema.sql'));$this->seedAccounts();}
        catch(Throwable $e){$this->connect_error=$e->getMessage();$this->pdo=null;}
    }
    public function set_charset($charset):bool{return true;}
    public function real_escape_string($input):string{return $this->pdo?substr($this->pdo->quote((string)$input),1,-1):addslashes((string)$input);}
    public function query($sql){
        if(!$this->pdo)return $this->fail('Database connection is not available.');
        try{$statement=$this->pdo->query($this->translateSql(trim($sql)));$this->affected_rows=$statement->rowCount();if($statement->columnCount())return new PgDBCompatResult($statement->fetchAll(PDO::FETCH_ASSOC));$this->updateInsertId();return true;}
        catch(PDOException $e){return $this->fail($e->getMessage());}
    }
    public function prepare($sql){
        if(!$this->pdo)return $this->fail('Database connection is not available.');
        try{return new PgDBCompatStatement($this->pdo->prepare($this->translateSql(trim($sql))),$this);}catch(PDOException $e){return $this->fail($e->getMessage());}
    }
    public function begin_transaction():bool{return $this->pdo?$this->pdo->beginTransaction():false;}
    public function commit():bool{return $this->pdo&&$this->pdo->inTransaction()?$this->pdo->commit():false;}
    public function rollback():bool{return $this->pdo&&$this->pdo->inTransaction()?$this->pdo->rollBack():false;}
    public function close():bool{$this->pdo=null;return true;}
    public function setError(string $error):void{$this->error=$error;}
    public function statementCompleted(int $count):void{$this->affected_rows=$count;$this->updateInsertId();}
    private function fail(string $error){$this->error=$error;$this->affected_rows=0;return false;}
    private function updateInsertId():void{try{$this->insert_id=(int)$this->pdo->lastInsertId();}catch(Throwable $e){}}

    private function translateSql(string $sql):string{
        if(preg_match("/^SHOW\\s+TABLES\\s+LIKE\\s+'([^']+)'/i",$sql,$m)){ $name=$this->real_escape_string($m[1]);return "SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name='$name'"; }
        if(preg_match('/^SHOW\\s+COLUMNS\\s+FROM\\s+([A-Za-z0-9_]+)/i',$sql,$m)){ $name=$this->real_escape_string($m[1]);return "SELECT column_name AS \"Field\",data_type AS \"Type\" FROM information_schema.columns WHERE table_schema='public' AND table_name='$name'"; }
        if(preg_match('/^ALTER TABLE .* MODIFY COLUMN/i',$sql))return 'SELECT 1';
        $sql=str_replace('`','"',$sql);
        $sql=preg_replace('/\\bBIGINT\\s+UNSIGNED\\s+AUTO_INCREMENT\\b/i','BIGINT GENERATED BY DEFAULT AS IDENTITY',$sql);
        $sql=preg_replace('/\\b(?:BIGINT|INT|INTEGER)\\s+AUTO_INCREMENT\\b/i','INTEGER GENERATED BY DEFAULT AS IDENTITY',$sql);
        $sql=preg_replace('/\\bTINYINT\\s*\\(1\\)/i','SMALLINT',$sql);
        $sql=preg_replace('/\\bDATETIME\\b/i','TIMESTAMP',$sql);
        $sql=preg_replace('/\\s+ON\\s+UPDATE\\s+CURRENT_TIMESTAMP/i','',$sql);
        $sql=preg_replace('/,\\s*INDEX\\s+[A-Za-z0-9_]+\\s*\\([^)]*\\)/i','',$sql);
        $sql=preg_replace('/\\bNOW\\s*\\(\\s*\\)/i','CURRENT_TIMESTAMP',$sql);
        $sql=preg_replace('/\\bCURDATE\\s*\\(\\s*\\)/i','CURRENT_DATE',$sql);
        $sql=preg_replace('/\\bIFNULL\\s*\\(/i','COALESCE(',$sql);
        $sql=preg_replace('/\\bYEAR\\s*\\(([^()]+)\\)/i','EXTRACT(YEAR FROM $1)',$sql);
        $sql=preg_replace('/\\bMONTH\\s*\\(([^()]+)\\)/i','EXTRACT(MONTH FROM $1)',$sql);
        $sql=preg_replace('/\\bDAY\\s*\\(([^()]+)\\)/i','EXTRACT(DAY FROM $1)',$sql);
        $sql=preg_replace("/DATE_FORMAT\\s*\\(([^,]+),\\s*'%Y-%m'\\)/i","TO_CHAR($1,'YYYY-MM')",$sql);
        $sql=preg_replace("/DATE_FORMAT\\s*\\(([^,]+),\\s*'%Y-%m-%d %H:%i:%s'\\)/i","TO_CHAR($1,'YYYY-MM-DD HH24:MI:SS')",$sql);
        $sql=preg_replace('/DATE_ADD\\s*\\(([^,]+),\\s*INTERVAL\\s+(\\d+)\\s+YEAR\\)/i',"($1 + INTERVAL '$2 year')",$sql);
        $sql=preg_replace('/DATE_SUB\\s*\\(([^,]+),\\s*INTERVAL\\s+(\\d+)\\s+DAY\\)/i',"($1 - INTERVAL '$2 day')",$sql);
        $sql=preg_replace('/DATE_SUB\\s*\\(([^,]+),\\s*INTERVAL\\s+(\\d+)\\s+MONTH\\)/i',"($1 - INTERVAL '$2 month')",$sql);
        if(preg_match('/^INSERT\\s+IGNORE\\s+/i',$sql)){$sql=preg_replace('/^INSERT\\s+IGNORE\\s+/i','INSERT ',$sql).' ON CONFLICT DO NOTHING';}
        if(stripos($sql,'ON DUPLICATE KEY UPDATE')!==false){
            preg_match('/^INSERT\\s+INTO\\s+([A-Za-z0-9_]+)/i',$sql,$m);$targets=['system_settings'=>'setting_key','payment_qr_settings'=>'payment_method','admin_profiles'=>'admin_id','admin_settings'=>'admin_id'];$target=$targets[strtolower($m[1]??'')]??null;
            if($target){$sql=preg_replace('/ON DUPLICATE KEY UPDATE/i',"ON CONFLICT ($target) DO UPDATE SET",$sql);$sql=preg_replace('/VALUES\\s*\\(\\s*([A-Za-z0-9_]+)\\s*\\)/i','EXCLUDED.$1',$sql);}
        }
        return $sql;
    }
    private function seedAccounts():void{
        $accounts=[['ADM-001','admin','Admin User','admin','admin123'],['STF-001','staff1','Sarah Staff','staff','staff123']];
        $stmt=$this->pdo->prepare('INSERT INTO admin_users(admin_id,username,username_lookup,password,full_name,role) VALUES(?,?,?,?,?,?) ON CONFLICT(admin_id) DO NOTHING');
        foreach($accounts as $a)$stmt->execute([$a[0],encrypt_sensitive($a[1]),sensitive_lookup($a[1]),password_hash($a[4],PASSWORD_DEFAULT),encrypt_sensitive($a[2]),$a[3]]);
        $stmt=$this->pdo->prepare('INSERT INTO rider_users(rider_id,username,username_lookup,password,full_name,contact_number,contact_lookup,status) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(rider_id) DO NOTHING');
        $stmt->execute(['RDR-001',encrypt_sensitive('rider1'),sensitive_lookup('rider1'),password_hash('rider123',PASSWORD_DEFAULT),encrypt_sensitive('Default Rider'),encrypt_sensitive('09990000001'),sensitive_lookup('09990000001'),'active']);
    }
}

if(!extension_loaded('pdo_pgsql'))die('Supabase requires the pdo_pgsql PHP extension.');
$conn=new PgDBCompatConnection(DB_HOST,DB_USER,DB_PASS,DB_NAME,DB_PORT);
if($conn->connect_error)die('Supabase connection failed: '.$conn->connect_error);
